<?php
namespace Ralphie\Sunshine;
use \stdClass;

class SlideController {

	public function __construct(
	\Monolog\Logger $logger){
		$this->log = $logger;
		$this->log->debug('SlideController Constructed');
	}
	/*
	{
  id          : "string" // will be autogenerated if omitted
  text        : "string" // node text
  icon        : "string" // string for custom
  state       : {
    opened    : boolean  // is the node open
    disabled  : boolean  // is the node disabled
    selected  : boolean  // is the node selected
  },
  children    : []  // array of strings or objects
  li_attr     : {}  // attributes for the generated LI node
  a_attr      : {}  // attributes for the generated A node
}
*/
	public function getSlideTree($conn, $msg) {
		
		$obj = new \StdClass;
		$obj->action = "dash.displaySlideTree";
		$obj->data = $this->getSubTree('exampleslides');

		$conn->send(json_encode($obj));
	}
	
	
	protected function getSubTree($directory) {
		
		$itt = new \FilesystemIterator($directory);
		$array = iterator_to_array($itt);
		
		$result = array();
		
		usort($array, function($a,$b){
			
			if($a->IsDir() && !$b->IsDir())return -1;
			if(!$a->IsDir() && $b->IsDir())return 1;
			return $a->getPathname() > $b->getPathname();
			});
		
		foreach($array as $file) {
			$obj = new \StdClass;
			$obj->id = $file->GetPathname();
			$obj->text = $file->GetFilename();
			$obj->icon = "glyphicon glyphicon-file icon-blue";
			if($file->IsDir()){
				$obj->children = $this->getSubTree($obj->id);
				$obj->icon = "glyphicon glyphicon-folder-open icon-yellow";
			}
			$result[] = $obj;
		}
		return $result;
		
	}
	
	
	protected function GetSlideList(){

		$slides = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator('exampleslides'),\RecursiveIteratorIterator::SELF_FIRST);
		$array = iterator_to_array($slides);
	
		foreach($array as $index => $file) {
			if($file->getFilename() == '..' OR $file->getFilename() == '.')unset($array[$index]);
			}
			
		usort($array, function($a,$b){
			return $a->getPathname() > $b->getPathname();
			});
		return($array);
	}
}